### ISSUE TITLE
Redux integration

### ISSUE THREAD

**Issue by lasher169** [sinnerschrader/aem-react#20]
Hi,

I read in another post that you have managed to integrate redux with your react components may I ask how did you do this and could you please provide examples.

Thanks

**Comment by stemey** [comment]
I tried to integrate redux as the underlying basis for managing the resources. I abandoned the idea because redux does not seem to work well with a generic application state like the content repository.  To make it work I had to pass the absolute content path to every single component which is very unintuitive for an AEM developer. So currently there is no redux support.

**Comment by lasher169** [comment]
all i want to do is tie the redux state to the components so that we can is to hold the state of the component is that possible ?

**Comment by stemey** [comment]
You can surely use redux to manage the custom state of the components. You should be able to apply the standard patterns. 
But the state that comes with loading the resources is currently managed in the components and the cache. That might be a problem - I don't know.

Unfortunately I currently don't have a lot of time to investigate this and I am still not completely convinced of the redux approach in general. There is a lot of loose coupling which is don't think is necessary and can make code hard to read. Also functional programming isn't everyone's cup of tea :)
