### ISSUE TITLE
Nashorn JS use and clientside rendering?

### ISSUE THREAD

**Issue by rahulagg** [sinnerschrader/aem-react#33]
Can you please explain the reason of use nashorn JS in this library.  Is it for compiling the .jsx file. Then how the react code gets mapped to .jsx files? What is the use of reactserver.js? is it only executed in author mode?

**Comment by stemey** [comment]
You are right, the nashorn engine is rendering the react components on the server. In the author mode only server rendering is enabled because react does not work well with the AEM javascript. Outside of the author mode the server rendering has two benefits. Firstly the user sees the content right away as it is served with the first request. Secondly it is seo friendly because crawlers can visit the page as it is served statically. Using the same rendering technology on the server and in the client is called universal (isomorphic) rendering and has a lot of benefits.
