### ISSUE TITLE
issue with multiple routing components in single aem page

### ISSUE THREAD

**Issue by player1466** [sinnerschrader/aem-react#35]
I have one aem page in which I am using one routing component (react component) and inside the parsys of that routing component, i am dragging another component having link (react component). The parent react routing component is working fine but the child routing component is not rendering properly. 
It is giving below error message -
http://localhost:4502/content/valichome/en/groupprofilemnt/jcr:content/par/my_plan_nav/content.json.html (not found)
http://localhost:4502/content/valichome/en/groupprofilemnt/jcr:content/par/my_plan_nav/content/more.json.html (not found)

So instead of "/my_plan_nav/" it should use "/administration_nav/" in the json path for child component

My actual content node structure is -
/content/valichome/en/administration/jcr:content/par/my_plan_nav/content/more/group_profile_nav - parent component
/content/valichome/en/groupprofilemnt/jcr:content/par/administration_nav/content/more - child component

Need help on this issue.

**Comment by stemey** [comment]
Can you post the whole router component, please?
Can you navigate the pages properly in the author mode? 

Is the Router in the same path relative to the page's resource path for all the pages? This is important because the content around the router must be the same for all pages in the SPA. That might be the problem:

page 1:
content/valichome/en/administration/
router component:
content/valichome/en/administration/jcr:content/par/my_plan_nav/content


page 1:
content/valichome/en/groupprofilemnt/
router component:?
content/valichome/en/groupprofilemnt/jcr:content/par/my_plan_nav/content

**Comment by stemey** [comment]
closed question due to inactivity
