### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by antonnyman** [sinnerschrader/aem-react#53]
Hello,

I have successfully installed aem-react with the archetype by following the docs.
Now when I go to /content/${siteName}/en.html I am met by a blank page.
Opening the console yields:

```
[..]
http://localhost:4502/content/reactdemo/overview/jcr:content/par/accordion.html?forceeditcontext=true&_=1494573393245 404 (Not Found)
[..]
```
What am I missing here?

**Comment by stemey** [comment]
Have you installed the react demo in that aem instance before? It does not work along side the archetype. You should deinstall the reactdemo package.

**Comment by antonnyman** [comment]
This is on a fresh install of AEM quickstart, so no.

**Comment by stemey** [comment]
But there is no accordion and no reactdemo path in the archetype. You might have installed the react demo package, please check your crx to make sure.

**Comment by antonnyman** [comment]
Even if I use the archetype or the demo I still get blank pages and the same error message.

Here is how:
* Starting a fresh AEM_6.3_Quickstart.jar
* Cloned the repo `git clone https://github.com/sinnerschrader/aem-react.git`
* Installed by `mvn clean install -PautoInstallPackage` (Success)
* Going to `http://localhost:4502/editor.html/content/reactdemo/cities.html`
* The page is blank and the console yields: `http://localhost:4502/content/reactdemo/overview/jcr:content/par/accordion.html?forceeditcontext=true&_=1494573393245 404 (Not Found)`

This happens both with the archetype and the demo (I don't have them installed in the same AEM)

**Comment by stemey** [comment]
The message suggests that the resource "/content/reactdemo/overview/jcr:content/par/accordion" doesn't exist. Can you please verify that. The maven command should deploy the content in your crx. The resource is part of:

https://github.com/sinnerschrader/aem-react/blob/master/demo/src/main/content/jcr_root/content/reactdemo/overview/.content.xml#L14

If the resource exists, then it might mean the resource cannot be rendered because the resourceType "react-demo/components/accordion" is not installed or the react bundle is not active (Search for react in the bundles console).

**Comment by danielrndm** [comment]
I don't now if you figure it out, but in my case, the generated pages (en and fr) contained paths to components in `demoapp\components\...` and the generated components folder is named after the artifact name, so it obviously doesn't match. In fact, I'm looking at this is the source code and I can confirm this. 

I had to replace every instance of demoapp in Eclipse with the name of my generated components folder and upload it. It now works fine
